// Trading Account Types

/**
 * Represents a trading account with balance, equity, and P&L tracking
 */
export interface TradingAccount {
  balance: number; // Available cash
  startingBalance: number; // Initial capital
  equity: number; // Balance + position values
  buyingPower: number; // Available for new trades
  totalPnL: number; // Total profit/loss ($)
  totalPnLPercent: number; // Total profit/loss (%)
}

// Order Types

/**
 * Represents a trading order
 */
export interface Order {
  id: string;
  symbol: string;
  side: "buy" | "sell";
  type: "market" | "limit" | "stop" | "stop_limit";
  quantity: number;
  price?: number; // For limit/stop orders
  stopPrice?: number; // For stop_limit orders
  status: "pending" | "filled" | "cancelled" | "rejected" | "partial";
  createdAt: number; // Timestamp
  filledAt?: number; // Timestamp when filled
  metadata?: any; // Custom data
}

// Position Types

/**
 * Represents an open trading position
 */
export interface Position {
  symbol: string;
  quantity: number;
  side: "long" | "short";
  avgEntryPrice: number;
  currentPrice: number;
  unrealizedPnL: number;
  unrealizedPnLPercent: number;
  entryTime: number;
  costBasis: number;
}

/**
 * P&L calculation result
 */
export interface PnLResult {
  unrealizedPnL: number;
  unrealizedPnLPercent: number;
  positionValue: number;
  costBasis: number;
}

// Trade Types

/**
 * Represents a completed transaction
 */
export interface Trade {
  id: string;
  orderId?: string;
  symbol: string;
  side: "buy" | "sell";
  quantity: number;
  price: number; // Execution price
  timestamp: number;
  type: "market" | "limit" | "stop";
  fees?: number; // Optional commission
  metadata?: any; // Custom data
}

/**
 * Represents a completed trade with entry and exit
 */
export interface CompletedTrade {
  id: string;
  symbol: string;
  side: "long" | "short";
  quantity: number;
  entryPrice: number;
  exitPrice: number;
  pnl: number; // Realized P&L
  pnlPercent: number; // Realized P&L %
  entryTime: number;
  exitTime: number;
  duration: number; // milliseconds
  fees?: number; // Optional commission
  notes?: string; // Trade journal notes
}

// Performance Metrics

/**
 * Performance analytics for a trading session
 */
export interface PerformanceMetrics {
  totalTrades: number;
  winningTrades: number;
  losingTrades: number;
  winRate: number; // Percentage
  avgWin: number;
  avgLoss: number;
  profitFactor: number; // avgWin / avgLoss
  totalPnL: number;
  totalPnLPercent: number;
  largestWin: number;
  largestLoss: number;
  avgTradeDuration: number; // milliseconds
  sharpeRatio: number;
  maxDrawdown: number; // Percentage
  expectancy: number; // Average $ per trade
}

// Strategy Types

/**
 * Trading strategy interface for backtesting
 */
export interface TradingStrategy {
  name: string;
  symbol: string;
  description?: string;

  /**
   * Returns list of required indicator IDs that this strategy needs
   * @returns Array of evaluator IDs (e.g., ["moving-averages", "rsi"])
   */
  getRequiredIndicators(): string[];

  /**
   * Called for each candle during backtest
   * @param candle Current price candle
   * @returns Order signal or null
   */
  onCandle(candle: any): OrderSignal | null;

  /**
   * Called when a trade executes
   * @param trade The executed trade
   */
  onTrade?(trade: Trade): void;

  /**
   * Optional initialization
   * @param account Initial account state
   */
  onStart?(account: TradingAccount): void;

  /**
   * Optional cleanup
   * @param metrics Final performance metrics
   */
  onEnd?(metrics: PerformanceMetrics): void;
}

/**
 * Order signal generated by a trading strategy
 */
export interface OrderSignal {
  side: "buy" | "sell";
  type: "market" | "limit";
  quantity: number;
  price?: number;
  stopLoss?: number;
  takeProfit?: number;
}

// Backtest Types

/**
 * Result of a backtest run
 */
export interface BacktestResult {
  strategy: string;
  symbol: string;
  startDate: Date;
  endDate: Date;
  metrics: PerformanceMetrics;
  trades: CompletedTrade[];
  equityCurve: EquityPoint[];
  drawdownCurve: DrawdownPoint[];
  account: TradingAccount;
}

/**
 * Data point in equity curve
 */
export interface EquityPoint {
  timestamp: number;
  equity: number;
}

/**
 * Data point in drawdown curve
 */
export interface DrawdownPoint {
  timestamp: number;
  drawdownPercent: number;
}

// Event Types

/**
 * Trading engine event types
 */
export type TradingEngineEvent =
  | "trade-executed"
  | "order-rejected"
  | "account-updated"
  | "position-updated"
  | "order-placed"
  | "order-cancelled"
  | "reset"
  | "progress"
  | "data-loaded";

/**
 * Event payload for trade-executed
 */
export interface TradeExecutedEvent {
  trade: Trade;
  position: Position;
}

/**
 * Event payload for order-rejected
 */
export interface OrderRejectedEvent {
  order: Order;
  reason: string;
}

/**
 * Event payload for position-updated
 */
export interface PositionUpdatedEvent {
  symbol: string;
  position: Position;
  pnl: PnLResult;
  timestamp?: number;
}

/**
 * Event payload for progress
 */
export interface ProgressEvent {
  current: number;
  total: number;
  percent: number;
  timestamp: number;
}

/**
 * Event payload for data-loaded
 */
export interface DataLoadedEvent {
  symbol: string;
  candleCount: number;
  startDate: Date;
  endDate: Date;
}

// Indicator Configuration Types

/**
 * Configuration for an indicator/evaluator with parameters
 */
export interface EvaluatorConfig {
  id: string; // Evaluator ID (e.g., "moving-averages", "rsi")
  params?: Record<string, any>; // Custom parameters for the indicator
}
